version: "2"
services:
  # https://docs.docker.com/compose/networking/

  kdc-kadmin:
    build: ./kdc-kadmin
    domainname: example.com
    env_file: kerberos.env
    ports:
      - "749:749"
      - "88:88"
    volumes:
      - /dev/urandom:/dev/random
  
  afs:
    build: ./afs
    hostname: afs
    domainname: example.com
    privileged: true
    env_file:
      - kerberos.env
      - afs.env
    environment:
      - KDC_KADMIN_SERVER=kdc-kadmin
    depends_on:
      - kdc-kadmin
    volumes:
      - ./afs:/tmp/afs

  afs-client:
    build: ./afs-client
    privileged: true
    env_file:
      - kerberos.env
      - afs.env
    environment:
      - KDC_KADMIN_SERVER=kdc-kadmin
      - AFS_SERVER=afs
    depends_on:
      - kdc-kadmin
      - afs
    volumes:
      - ./afs-client:/tmp/afs-client
      - ../:/tmp/project
