FROM debian:stable
MAINTAINER Rui Botelho "rui.botelho@tecnico.ulisboa.pt

RUN apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y krb5-kdc krb5-admin-server \
    openafs-client openafs-modules-dkms openafs-krb5 openafs-fileserver openafs-dbserver




